---
version: '3'

################################################################################
# SERVICES
################################################################################
services:
  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php: &php
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION:-8.0-work}
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/default

    environment:
      NEW_UID: 1000
      NEW_GID: 1000
      DEBUG_ENTRYPOINT: '2'
      DEBUG_COMPOSE_ENTRYPOINT: '2'
      DOCKER_LOGS: '1'
      COMPOSER_MEMORY_LIMIT: '-1'
      COMPOSER_POOL_OPTIMIZER: '0'

    volumes:
      - .:/var/www/default:rw

  # ------------------------------------------------------------
  # Apache Web Server
  # ------------------------------------------------------------
  httpd:
    image: devilbox/apache-2.4:alpine
    container_name: httpd
    restart: unless-stopped

    environment:
      NEW_UID: 1000
      NEW_GID: 1000
      MAIN_VHOST_ENABLE: 1
      MAIN_VHOST_DOCROOT_DIR: site
      PHP_FPM_ENABLE: 1
      PHP_FPM_SERVER_ADDR: php
      PHP_FPM_SERVER_PORT: 9000
      PHP_FPM_TIMEOUT: 180
      MAIN_VHOST_BACKEND: conf:phpfpm:tcp:php:9000

    ports:
      - '8080:80'

    volumes:
      - .:/var/www/default:ro

    depends_on:
      - php

  # ------------------------------------------------------------
  # MySQL Database
  # ------------------------------------------------------------
  mysql:
    image: mariadb:${MYSQL_VERSION:-10.6}
    container_name: mysql
    restart: unless-stopped

    ports:
      - '3306:3306'

    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}'
      MYSQL_USER: '${MYSQL_PASSWORD:-espocrm}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-espocrm}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-espocrm}'

    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql: {}
